### PR TITLE
Support for known proteins

### PR DESCRIPTION
**Pull request by husensofteng**
The protheaders parameter may have a prefix indicating if any or all proteins in the matching list should be considered. 
If the prefix is 'known' then the psm is returned if any of the proteins match the given headers whereas for other prefixes all proteins in the list should match the given headers. 
Input example for protheaders: known:^ENSP;?^decoy_ENSP or var:^lncRNA;^decoy_lncRNA.

### CODE REVIEW

**Comment by glormph** [comment]
I think this looks good, but does it assume that the canonical header is the first element? In that case there'd be different logic (break as soon as found) for known and other headers if one doesnt specify a header. Maybe a good idea if we create an option like `--knownheaders` to catch the knownheader. (I can do that)

**Comment by husensofteng** [comment]
it always takes the first part from the split on `|` as known and the second part (if any) as other class. In case there is only one part it is considers it as known, because it does not filter against anything. 

`can_headers = protheaders.split('|')[0].split(':')[-1].strip(';').split(';')
  other_headers = protheaders.split('|')[-1].split(':')[-1].strip(';').split(';')
`

So technically there is nothing about known (canonical) it is just filtering tags in the second part of the split against the first part of the split.

**Comment by glormph** [comment]
Maybe I am not understanding this correctly, but in case of `--protheaders 'novel_|variant_'` you'd filter the novel ones as known, meaning you'll lose the peptides which are both novel and variant?
Since the filtering process is different for `can_headers`, maybe we should have a separate option for that?

**Comment by glormph** [comment]
I'll merge and keep working on it! Thanks!

**Pull request merged**
